### ISSUE TITLE
COTH thermal model now requires frequency as well as s-matrix for passive multiport covariance calculation

### ISSUE THREAD

**Issue by mgrando** [rdireen/scikit-rf#10]
I added the coth thermal model. It may have broke some of your stuff especially when calculating noise for z and y covariance matrices.  Need to add a test for this or at least track down any instance where those functions are used.

**Comment by rdireen** [comment]
Tested the code after the new coth update. Everything works as it did before the upgrade. It would be good to get to unit testing soon so these tests are automatic.

**Comment by mgrando** [comment]
Agreed. I think examples and tests are the next steps.

Maurio
